### ISSUE TITLE
script cannot write to /tmp

### ISSUE THREAD

**Issue by diwanicki** [rtrouton/autopkg-conductor#1]
This is occurring in macOS 10.15.5:

> /usr/local/bin/autopkg-conductor.sh: line 137: /tmp/autopkg.out: Permission denied
/usr/local/bin/autopkg-conductor.sh: line 142: /tmp/autopkg.out: Permission denied
/usr/local/bin/autopkg-conductor.sh: line 145: /tmp/autopkg.out: Permission denied
/usr/local/bin/autopkg-conductor.sh: line 146: /tmp/autopkg_error.out: Permission denied
/usr/local/bin/autopkg-conductor.sh: line 147: /tmp/autopkg_error.out: Permission denied
/usr/local/bin/autopkg-conductor.sh: line 148: /tmp/autopkg_error.out: Permission denied
/usr/local/bin/autopkg-conductor.sh: line 149: /tmp/autopkg.out: Permission denied
/usr/local/bin/autopkg-conductor.sh: line 178: /tmp/autopkg.out: Permission denied
/usr/local/bin/autopkg-conductor.sh: line 184: /tmp/autopkg.out: Permission denied
/usr/local/bin/autopkg-conductor.sh: line 187: /tmp/autopkg.out: Permission denied
/usr/local/bin/autopkg-conductor.sh: line 191: /tmp/autopkg_error.out: Permission denied
/usr/local/bin/autopkg-conductor.sh: line 192: /tmp/autopkg_error.out: Permission denied
/usr/local/bin/autopkg-conductor.sh: line 193: /tmp/autopkg_error.out: Permission denied

**Comment by rtrouton** [comment]
Unable to reproduce.
