### ISSUE TITLE
Unnecessary error info gets sent to Slack

### ISSUE THREAD

**Issue by sgmills** [rtrouton/autopkg-conductor#3]
When running autopkg conductor with a Slack webhook we often get several lines that look something like this in Slack:

% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
End of error log for AutoPkg run

**Comment by rtrouton** [comment]
Does this information also show up as errors in the logs created in ~/Library/Logs? The reason I'm asking is that if they show up in the error log, AutoPkg thinks they're errors and that's how they're ultimately winding up in Slack.

**Comment by sgmills** [comment]
Yes, the block below is what's showing up in the log file, so that explains why it's getting sent. I was thinking about creating a fork and adding an if statement to the SendToSlack function that just drops any lines that look like that. Just wanted to check if you had heard of this before I put in the effort!

```
Error log for AutoPkg run to
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 63846    0 63846    0     0  92795      0 --:--:-- --:--:-- --:--:-- 94307
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 11  149M    0     0   11 17.6M      0  17.9M  0:00:08 --:--:--  0:00:08 18.2M
 46  149M    0     0   46 69.9M      0  35.2M  0:00:04  0:00:01  0:00:03 35.4M
 82  149M    0     0   82  122M      0  41.0M  0:00:03  0:00:02  0:00:01 41.2M
100  149M    0   382  100  149M     94  36.9M  0:00:04  0:00:04 --:--:-- 37.0M
100  149M    0   382  100  149M     94  36.9M  0:00:04  0:00:04 --:--:-- 37.0M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   331    0     0  100   331      0   1204 --:--:-- --:--:-- --:--:--  1282
```

**Comment by rtrouton** [comment]
Nope, this is new to me.
